import Head from "next/head";
import useSWR from "swr";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { fetcher } from "../lib/utils";
import ImageCard from "../components/ImageCard";

export default function Home() {
  const [searchKeyword, setSearchKeyword] = useState("");
  const { data } = useSWR(`/api/search/${searchKeyword ? searchKeyword : "Ukraine"}`, fetcher);

  return (
    <div className={styles.container}>
      <Head>
        <title>Bel Art</title>
        <meta name="description" content="Image Gallery Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Bel Art Gallery</h1>
        <input
          type="text"
          name="Search"
          value={searchKeyword}
          onChange={(e) => setSearchKeyword(e.target.value)}
        />
        {data ? (
          <div className="image-container">
            {data.hits.map((post) => (
              <ImageCard post={post} />
            ))}
          </div>
        ) : (
          <div>Loading...</div>
        )}
      </main>
    </div>
  );
}
