import Head from "next/head";
import useSWR from "swr";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home({ posts }) {
  const fetcher = (url) => fetch(url).then((r) => r.json());
  const [searchKeyword, setSearchKeyword] = useState("");

  const { data, error } = useSWR(
    `/api/search/${searchKeyword ? searchKeyword : "Ukraine"}`,
    fetcher
  );

  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Bel Art Gallaire</h1>
        <input
          type="text"
          name="Search"
          value={searchKeyword}
          onChange={(e) => setSearchKeyword(e.target.value)}
        />
      </main>
      {data ? (
        <div>
          {data.hits.map((post) => (
            <div key={post.id}>
              <Image
                src={post.previewURL}
                alt={post.tags}
                height={post.previewHeight}
                width={post.previewWidth}
              />
              <p>{post.tags}</p>
            </div>
          ))}
        </div>
      ) : (
        <div>Loading...</div>
      )}
    </div>
  );
}
